# VisageFour\PersonBundle\config\services.yml
services:
    visage_four.base_person_manager:
        class: VisageFour\Bundle\PersonBundle\Services\BasePersonManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - 'VisageFour\Bundle\PersonBundle\Entity\BasePerson'
            - "@event_dispatcher"
            - "@logger"