<?php

namespace VisageFour\Bundle\PersonBundle\Repository;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * BasePersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePersonRepository extends ServiceEntityRepository
{
}
