<?php

namespace VisageFour\Bundle\PersonBundle\Repository;

/**
 * basePersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basePersonRepository extends \Doctrine\ORM\EntityRepository
{
}
