# VisageFour\PeronBundle\config\services.yml
services:
    VisageFour.PersonManager:
        class: VisageFour\Bundle\PersonBundle\Services\BasePersonManager
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher" "@logger", "PersonBundle:BasePerson"]
